### ISSUE TITLE
cant build with wxwidgets 3.2.0

### ISSUE THREAD

**Issue by trufae** [Moonslate/MoonHex#2]
```
MoonHex/src/dialog_preferences.cpp:14:18: error: no member named 'SetMin' in 'wxSpinCtrl'
        m_fontSizeSpin->SetMin(1);
        ~~~~~~~~~~~~~~  ^
1 warning and 1 error generated.
```

**Comment by andrey-moura** [comment]
@trufae, try using [SetRange](https://docs.wxwidgets.org/3.0/classwx_spin_ctrl.html#ab2b5d966f0895c5cc4d54a9cfd1817dd) (int minVal, int maxVal) instead of  SetMin and SetMax.

**Comment by trufae** [comment]
Yep that works
